### ISSUE TITLE
Add a component with a CLI

### ISSUE THREAD

**Issue by anxest** [tikui/tikui#16]
Hello,

I'm starting to use Tikui wich is awesome so far to render elements out of context and allow me to improve the use cases. One of my problems is that it's quite exhaustive to create all the files for each component. I think a command or a form could be used to generate those (asking for the component category, the component name, and a class or an id, I guess). Do you think something like this can be added ?

**Comment by Gnuk** [comment]
I think it's a good idea, with something like `npm run component:create atom/button` for example.

What do you think about it @tikui/developers ?

**Comment by hdurix** [comment]
Yes good idea, maybe something more friendly `tikui atom button`.

**Comment by Gnuk** [comment]
Hum I think we should challenge it for non atomic design project, so it will be more something in that way:

```
tikui component atom/button
```

With:

* `tikui` represents the command service
* `component` represents a component doc generation (because there is also template documentation for example)
* `atom/button` is the path to the new component, where `atom` is a folder and `button` is the component name

**Comment by nonomoho** [comment]
I agree too, very good idea !

**Comment by jeremietisserand** [comment]
Good idea ! 
It would be very useful to automatically generate a component.

**Comment by nonomoho** [comment]
I can work on it using commander. I think using TypeScript and Jest will be useful and necessary  to do it. I wait #21 and #7 before push my first version as a draft. 

I think #21 can be merge and then #7 can be done easily. 

I see that with @Gnuk asap.

**Comment by Gnuk** [comment]
It's progressing following tikui/tikui-cli#1

**Comment by Gnuk** [comment]
So it's done, I close this issue
