### ISSUE TITLE
Gitignore

### ISSUE THREAD

**Issue by anxest** [tikui/tikui#17]
Could we gitignore all the content of /atom, /molecule, etc but the initial pug file?

Instead of working with Tikui, my IDE tells me I'm improving the tikui app ^^

```
# Ignore everything
atom/*

# But not these files...
!atom/atom.pug
# etc...
```

Ideally, the content of atom.pug should be ignored too, and  this part shouldn't be edited by users, imo but include  a file that list the components users added by themselves: 
```
extends /layout-documentation

block append vars
  -active='atom'

block title
  title Tikui - Atoms

block content
  .container
    h1 Atoms

include /documentation/atomic-design/quote/atom
```

**Comment by Gnuk** [comment]
Hi @anxest , thank you for your issue but I think the purpose of Tikui (after some releases) is to be only dependencies inside a `package.json` instead of having `documentation`, `tech` and a predefined structure.

There will be some plans inside #9 and #10 issue to know how we do it.

I suppose we will have : 

* A documentation part as a dependency
* Tech part will be moved in a dependency
* The structure will not be present and there will have a command to generate it using something like: 
  ```
  npm run structure:generate atomic
  ```

So, to resume, It's important to not add those files inside a `.gitignore` because if you do that, you can't version your own components.

… And later, there will be some tools to generate this structure and it will be more easy to understand the structure because we will remove a lot of technical part in the structure.

**Comment by anxest** [comment]
That makes sense, thanks for your answer :)
