### ISSUE TITLE
Init CI / CD

### ISSUE THREAD

**Issue by jeremietisserand** [tikui/tikui#5]
Init CI / CD pipeline to deploy the Tikui on an environment.

**Comment by pascalgrimaud** [comment]
Which CICD do you plan to use ?
- Travis CI
- Azure Pipelines
- Circle CI

**Comment by Gnuk** [comment]
The more compatible for a free software solution, maybe not hard to use or maintain.

What do you think we should use ?

**Comment by pascalgrimaud** [comment]
Travis: if you want to do this quickly, it's the easier, but Travis is dying...
Azure Pipelines: maybe the best because of 10 parallel builds, but you won't use all the builds so maybe too much
Circle CI: the UI is really cool

@Gnuk : so the choice is yours, as you're the Tech Lead of this project. I'll just help @nonomoho to integrate the CICD

**Comment by Gnuk** [comment]
In fact I don't know if we will go to Gitlab.com and use Gitlab CI or if we will use something like Circle CI.
